import "./globals.css";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";

const manrope = Manrope({ subsets: ["latin", "latin-ext"] });
export const poppins = Poppins({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-display",
  fallback: ["Times New Roman", "Times", "serif"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Salemkode website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="overflow-x-hidden" lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta content="Astro description" name="description" />
        <meta content="width=device-width" name="viewport" />
        <link href="/favicon.png" rel="icon" type="image/svg+xml" />
      </head>
      <body
        className={`max-w-full overflow-y-auto overflow-x-hidden ${manrope.className} ${poppins.variable}`}
      >
        <NavBar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
