import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import type { Metadata } from "next";
import { Gabarito, Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin", "latin-ext"] });
export const lora = Gabarito({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-lora",
  fallback: ["Times New Roman", "Times", "serif"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="Astro description" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body
        className={`overflow-y-auto overflow-x-hidden ${manrope.className} ${lora.variable}`}
      >
        <NavBar />
        <div>{children}</div>
        <footer />
      </body>
    </html>
  );
}
